### ISSUE TITLE
SPI from accelerometer

### ISSUE THREAD

**Issue by Kv1n20** [BTSC10/Oreo#9]

**Comment by BTSC10** [comment]
H3LIS331DLTR

**Comment by Kv1n20** [comment]
Using HAL

**Comment by Kv1n20** [comment]
https://controllerstech.com/how-to-use-spi-with-stm32/
https://stackoverflow.com/questions/53122936/stm32-spi-communication

**Comment by BTSC10** [comment]
just for reference these are the initial params we need to set for the SPI interface

![image](https://user-images.githubusercontent.com/80358316/224164787-292d42dc-af5e-496c-a261-b80aa43f60d2.png)

**Comment by BTSC10** [comment]
changed CPOL = 1, CPHA = 1 to match datasheet timing diagram

MISO line and clock
![image](https://github.com/BTSC10/Oreo/assets/80358316/788e12b9-aa65-41f2-bb50-d7bcb87b5652)

MOSI line and clock
![image](https://github.com/BTSC10/Oreo/assets/80358316/000399b2-f0c1-40dc-b417-c322eddafea6)

during the first 8 clock pulses, the MISO line sends out 0b10001111 trying to read WHO-AM-I
during the next 8 cycles the MISO line sends out junk (the same bytes)

the MOSI line responds with 0b00110100 during the second byte of clock pulses but also sends out this data during the first byte. This is not expected and not shown in the datasheet

**Comment by BTSC10** [comment]
Ok I think the issue is the Chip select pin on the accelerometer. It hardwired to ground as it is the only device on the SPI bus but that might be causing issues (https://electronics.stackexchange.com/questions/273157/can-ss-pin-be-tied-low-if-only-one-spi-device-is-used). The accel chip might need the pin to be pulled low before each transmission and brought back high afterwards

every time the device is power cycled, it responds to the first request sent to it. After that it just repeats that byte over and over no matter what request is made. This would explain why we are seeing a response in the first 8 bits of each transmission as well as the second.

To fix this we either need to try and bodge the PCB or design a v2:
This is the current design and pin 8 is the SPI enable/chip select pin. It would probably be easy to cut the trace that leads to pin 8. The issue would be getting a wire to that pin/pad during or after assembly. The grey box (AC1) shows the rough footprint of the accelerometer chip. 
![image](https://github.com/BTSC10/Oreo/assets/80358316/98b13a62-1815-4075-9b23-bb8d1e289660)

**Comment by BTSC10** [comment]
PCB V1.1 added CHIP SELECT signal. SPI and AC1 tested and working
